In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler , Normalizer
from sklearn import metrics
%matplotlib inline

In [ ]:
from google.colab import files
upload = files.upload()

Saving Cleaned-Data.csv to Cleaned-Data.csv

## Eksplorasi data

In [ ]:
data = pd.read_csv("Cleaned-Data.csv")
data

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Gender_Male,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country
0,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,0,0,1,China
1,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,0,1,0,China
2,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,1,0,0,China
3,1,1,1,1,1,0,1,1,1,1,...,1,0,0,1,0,0,0,0,1,China
4,1,1,1,1,1,0,1,1,1,1,...,1,0,0,1,0,0,0,1,0,China
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316795,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,Other
316796,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,1,0,0,Other
316797,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,0,0,1,Other
316798,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,0,1,0,Other
316799,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,1,0,0,Other

In [ ]:
data.shape

(316800, 27)

In [ ]:
#melihat semua fitur yang ada
data.columns

Index(['Fever', 'Tiredness', 'Dry-Cough', 'Difficulty-in-Breathing',
       'Sore-Throat', 'None_Sympton', 'Pains', 'Nasal-Congestion',
       'Runny-Nose', 'Diarrhea', 'None_Experiencing', 'Age_0-9', 'Age_10-19',
       'Age_20-24', 'Age_25-59', 'Age_60+', 'Gender_Female', 'Gender_Male',
       'Gender_Transgender', 'Severity_Mild', 'Severity_Moderate',
       'Severity_None', 'Severity_Severe', 'Contact_Dont-Know', 'Contact_No',
       'Contact_Yes', 'Country'],
      dtype='object')

In [ ]:
#melihat banyak kelas
data['Country'].unique()

array(['China', 'Italy', 'Iran', 'Republic of Korean', 'France', 'Spain',
       'Germany', 'UAE', 'Other-EUR', 'Other'], dtype=object)

In [ ]:
data.isnull().sum() #mengecek apakah ada data yang hilang

Fever                      0
Tiredness                  0
Dry-Cough                  0
Difficulty-in-Breathing    0
Sore-Throat                0
None_Sympton               0
Pains                      0
Nasal-Congestion           0
Runny-Nose                 0
Diarrhea                   0
None_Experiencing          0
Age_0-9                    0
Age_10-19                  0
Age_20-24                  0
Age_25-59                  0
Age_60+                    0
Gender_Female              0
Gender_Male                0
Gender_Transgender         0
Severity_Mild              0
Severity_Moderate          0
Severity_None              0
Severity_Severe            0
Contact_Dont-Know          0
Contact_No                 0
Contact_Yes                0
Country                    0
dtype: int64

## Pre-processing

### Grouping fitur yang mirip

In [ ]:
#terlihat ada beberapa fitur yang sama, tetapi terpisah (Age, Gender, Severity, Contact)

#terlihat ada beberapa fitur yang sama, tetapi terpisah (Age, Gender, Severity, Contact)

severity_columns = data.filter(like='Severity_').columns

data['Severity_None'].replace({1:'None',0:'No'},inplace =True)
data['Severity_Mild'].replace({1:'Mild',0:'No'},inplace =True)
data['Severity_Moderate'].replace({1:'Moderate',0:'No'},inplace =True)
data['Severity_Severe'].replace({1:'Severe',0:'No'},inplace =True)

data['Condition'] = data[severity_columns].values.tolist()

def removing(list1):
    list1 = set(list1) 
    list1.discard("No")
    a = ''.join(list1)
    return a

data['Condition'] = data['Condition'].apply(removing)


age_columns = data.filter(like='Age_').columns

data['Age_0-9'].replace({1:'0-9',0:'No'},inplace =True)
data['Age_10-19'].replace({1:'10-19',0:'No'},inplace =True)
data['Age_20-24'].replace({1:'20-24',0:'No'},inplace =True)
data['Age_25-59'].replace({1:'25-59',0:'No'},inplace =True)
data['Age_60+'].replace({1:'60+',0:'No'},inplace =True)

data['Age'] = data[age_columns].values.tolist()

def removing(list2):
    list2 = set(list2) 
    list2.discard("No")
    b = ''.join(list2)
    return b

data['Age'] = data['Age'].apply(removing)

gender_columns = data.filter(like='Gender_').columns

data['Gender_Female'].replace({1:'Female',0:'No'},inplace =True)
data['Gender_Male'].replace({1:'Male',0:'No'},inplace =True)
data['Gender_Transgender'].replace({1:'Transgender',0:'No'},inplace =True)

data['Gender'] = data[gender_columns].values.tolist()

def removing(list3):
    list3 = set(list3) 
    list3.discard("No")
    c = ''.join(list3)
    return c

data['Gender'] = data['Gender'].apply(removing)


contact_columns = data.filter(like='Contact_').columns

data['Contact_Dont-Know'].replace({1:'Dont-Know',0:'No'},inplace =True)
data['Contact_No'].replace({1:'Not',0:'No'},inplace =True)
data['Contact_Yes'].replace({1:'Yes',0:'No'},inplace =True)

data['Contact'] = data[severity_columns].values.tolist()

def removing(list4):
    list4 = set(list4) 
    list4.discard("No")
    d = ''.join(list4)
    return d

data['Contact'] = data['Contact'].apply(removing)

data

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country,Condition,Age,Gender,Contact
0,1,1,1,1,1,0,1,1,1,1,...,No,No,No,No,Yes,China,Mild,0-9,Male,Mild
1,1,1,1,1,1,0,1,1,1,1,...,No,No,No,Not,No,China,Mild,0-9,Male,Mild
2,1,1,1,1,1,0,1,1,1,1,...,No,No,Dont-Know,No,No,China,Mild,0-9,Male,Mild
3,1,1,1,1,1,0,1,1,1,1,...,No,No,No,No,Yes,China,Moderate,0-9,Male,Moderate
4,1,1,1,1,1,0,1,1,1,1,...,No,No,No,Not,No,China,Moderate,0-9,Male,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316795,0,0,0,0,0,1,0,0,0,0,...,No,Severe,No,Not,No,Other,Severe,60+,Transgender,Severe
316796,0,0,0,0,0,1,0,0,0,0,...,No,Severe,Dont-Know,No,No,Other,Severe,60+,Transgender,Severe
316797,0,0,0,0,0,1,0,0,0,0,...,None,No,No,No,Yes,Other,None,60+,Transgender,None
316798,0,0,0,0,0,1,0,0,0,0,...,None,No,No,Not,No,Other,None,60+,Transgender,None
316799,0,0,0,0,0,1,0,0,0,0,...,None,No,Dont-Know,No,No,Other,None,60+,Transgender,None

### Membuat Data Frame Baru

In [ ]:
#memilih fitur yang akan digunakan
new_data = data[['Fever', 'Tiredness', 'Dry-Cough', 'Difficulty-in-Breathing',
       'Sore-Throat', 'None_Sympton', 'Pains', 'Nasal-Congestion',
       'Runny-Nose', 'Diarrhea', 'None_Experiencing', 'Age','Condition', 'Gender', 'Contact',
       'Country']]
new_data

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,None_Experiencing,Age,Condition,Gender,Contact,Country
0,1,1,1,1,1,0,1,1,1,1,0,0-9,Mild,Male,Mild,China
1,1,1,1,1,1,0,1,1,1,1,0,0-9,Mild,Male,Mild,China
2,1,1,1,1,1,0,1,1,1,1,0,0-9,Mild,Male,Mild,China
3,1,1,1,1,1,0,1,1,1,1,0,0-9,Moderate,Male,Moderate,China
4,1,1,1,1,1,0,1,1,1,1,0,0-9,Moderate,Male,Moderate,China
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316795,0,0,0,0,0,1,0,0,0,0,1,60+,Severe,Transgender,Severe,Other
316796,0,0,0,0,0,1,0,0,0,0,1,60+,Severe,Transgender,Severe,Other
316797,0,0,0,0,0,1,0,0,0,0,1,60+,None,Transgender,None,Other
316798,0,0,0,0,0,1,0,0,0,0,1,60+,None,Transgender,None,Other
316799,0,0,0,0,0,1,0,0,0,0,1,60+,None,Transgender,None,Other

In [ ]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316800 entries, 0 to 316799
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Fever                    316800 non-null  int64
 1   Tiredness                316800 non-null  int64
 2   Dry-Cough                316800 non-null  int64
 3   Difficulty-in-Breathing  316800 non-null  int64
 4   Sore-Throat              316800 non-null  int64
 5   None_Sympton             316800 non-null  int64
 6   Pains                    316800 non-null  int64
 7   Nasal-Congestion         316800 non-null  int64
 8   Runny-Nose               316800 non-null  int64
 9   Diarrhea                 316800 non-null  int64
 10  None_Experiencing        316800 non-null  int64
 11  Age                      316800 non-null  object
 12  Condition                316800 non-null  object
 13  Gender                   316800 non-null  object
 14  Contact                  316800 non-null  object
 15  Country                  316800 non-null  object
dtypes: int64(11), object(5)
memory usage: 38.7+ MB

In [ ]:
from sklearn import preprocessing

le_cond = preprocessing.LabelEncoder()
le_cond.fit(['None', 'Mild', 'Moderate', 'Severe'])
new_data['Condition'] = le_cond.fit_transform(new_data['Condition'])

le_country = preprocessing.LabelEncoder()
le_country.fit(['China', 'Italy', 'Iran', 'Republic of Korean', 'France', 
                'Spain','Germany', 'UAE', 'Other-EUR', 'Other'])
new_data['Country'] = le_country.fit_transform(new_data['Country'])

le_age = preprocessing.LabelEncoder()
le_age.fit(['0-9','10-19','20-24','25-59','60+'])
new_data['Age'] = le_age.fit_transform(new_data['Age'])

le_gender = preprocessing.LabelEncoder()
le_gender.fit(['Female','Male','Transgender'])
new_data['Gender'] = le_gender.fit_transform(new_data['Gender'])

le_contact = preprocessing.LabelEncoder()
le_contact.fit(['Dont-Know','No','Yes'])
new_data['Contact'] = le_contact.fit_transform(new_data['Contact'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
new_data.describe()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,None_Experiencing,Age,Condition,Gender,Contact,Country
count,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000,316800.000000
mean,0.312500,0.500000,0.562500,0.500000,0.312500,0.062500,0.363636,0.545455,0.545455,0.363636,0.090909,2.000000,1.500000,1.000000,1.500000,4.500000
std,0.463513,0.500001,0.496079,0.500001,0.463513,0.242062,0.481046,0.497930,0.497930,0.481046,0.287480,1.414216,1.118036,0.816498,1.118036,2.872286
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.750000,0.000000,0.750000,2.000000
50%,0.000000,0.500000,1.000000,0.500000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,1.500000,1.000000,1.500000,4.500000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,2.250000,2.000000,2.250000,7.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,3.000000,2.000000,3.000000,9.000000

In [ ]:
new_data['Country'].unique()

array([0, 4, 3, 7, 1, 8, 2, 9, 6, 5])

In [ ]:
#urutan country

country = ['China','France','Germany',
'Iran','Italy','Other','Other-EUR',
'Republic of Korean','Spain','UAE',]

In [ ]:
new_data

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,None_Experiencing,Age,Condition,Gender,Contact,Country
0,1,1,1,1,1,0,1,1,1,1,0,0,0,1,0,0
1,1,1,1,1,1,0,1,1,1,1,0,0,0,1,0,0
2,1,1,1,1,1,0,1,1,1,1,0,0,0,1,0,0
3,1,1,1,1,1,0,1,1,1,1,0,0,1,1,1,0
4,1,1,1,1,1,0,1,1,1,1,0,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316795,0,0,0,0,0,1,0,0,0,0,1,4,3,2,3,5
316796,0,0,0,0,0,1,0,0,0,0,1,4,3,2,3,5
316797,0,0,0,0,0,1,0,0,0,0,1,4,2,2,2,5
316798,0,0,0,0,0,1,0,0,0,0,1,4,2,2,2,5
316799,0,0,0,0,0,1,0,0,0,0,1,4,2,2,2,5

In [ ]:
#Ubah value fitur-fitur menjadi array 2D untuk diolah sebagai X dan y
X = np.asarray(new_data[['Fever', 'Tiredness', 'Dry-Cough', 'Difficulty-in-Breathing',
       'Sore-Throat', 'None_Sympton', 'Pains', 'Nasal-Congestion',
       'Runny-Nose', 'Diarrhea', 'None_Experiencing', 'Age','Condition', 'Gender', 'Contact']].values)
print('X : ',X)

Y = np.asarray(new_data[['Country']].values)
print('\nY : ',Y)

X :  [[1 1 1 ... 0 1 0]
 [1 1 1 ... 0 1 0]
 [1 1 1 ... 0 1 0]
 ...
 [0 0 0 ... 2 2 2]
 [0 0 0 ... 2 2 2]
 [0 0 0 ... 2 2 2]]

Y :  [[0]
 [0]
 [0]
 ...
 [5]
 [5]
 [5]]

# Membagi Train dan Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)

In [ ]:
print("X_train: ", X_train.shape)
print("Y_train: ", Y_train.shape)
print("X_test: ", X_test.shape)
print("Y_test: ", Y_test.shape)

X_train:  (253440, 15)
Y_train:  (253440, 1)
X_test:  (63360, 15)
Y_test:  (63360, 1)

In [ ]:
X_valid, X_trainX = X_train[:150000]/255.0, X_train[150000:]/255.0
y_valid, y_trainX = Y_train[:150000], Y_train[150000:]

# Membuat Model

In [ ]:
pip install keras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: keras in /usr/local/lib/python3.7/dist-packages (2.8.0)

In [ ]:
import keras
import tensorflow as tf

!pip install -q -U keras-tuner

import keras_tuner as kt

     |████████████████████████████████| 133 kB 5.2 MB/s

In [ ]:
def build_model(hp):
  model = keras.models.Sequential() #kita inisialisasi terlebih dahul model sequential
  

  hp_layers = hp.Choice('layer', [3,10]) # kita mulai mendefinisikan variabel
  hp_neurons = hp.Int('neuron', min_value = 100, max_value = 500, step = 50)
  #terdapat 2 variabel yaitu hp layer dan neurons. hp.choice maksudnya ialah ingin memvariasikan nilai layer nya itu bisa 2 atau 3
  #hp.int itu akan memvariasikan nilai neuron dengan minimal value nya 100 dan max nya 300 step nya 200. Artinya nilai2 yang mungkin pada hp neuron itu 100 200 dan 300.
  #disini kita akan memiliki beberapa kombinasi, (cont : kita punya arsitekturnya itu 2 hidden layer dan disetiap hidden layer nya itu punya 100 neuron atau bisa jg kita punya 3 hiden layer dengan 200 neuron)

  for layers in range(hp_layers): #kalo misalkan hp layersnya itu 3 maka dia akan mengulang 3 kali
    model.add(keras.layers.Dense(hp_neurons, activation = 'relu')) #kita akan mebuat 3 hidden layer(model.add) dimana banyaknya neuronnya itu (hp neuron)
  model.add(keras.layers.Dense(10, activation = 'softmax')) #output layer nya ada 10 neuron dan 20 nilai output

  #arsitektur model nya sudah selesai dibuat lalu kita akan lakukan kompilasi

  optimizer = tf.keras.optimizers.Adam()
  model.compile(loss = 'sparse_categorical_crossentropy',
                 optimizer = optimizer,
                 metrics = ['accuracy'])
  return model

In [ ]:
##sekarang akan dibuat hyperparameter turning nya
#hyperband tuner
tuner = kt.Hyperband(build_model,
                     objective = 'val_accuracy',
                     max_epochs = 25,
                     directory = 'my_di',
                     project_name = 'my_tuner') #disimpan dalam var tuner
#penjelasannya = objektif nya menggunakan akurasi pada data validasi (yang akan menjadi tolak ukur dari keakuratan
#tuning), max epochs nya, directory (lokasi dmn file tuning akan disimpan (namainnya terserah apa aja))

In [ ]:
stop_early = tf.keras.callbacks.EarlyStopping(
    monitor = 'val_loss',
    patience = 5
)

In [ ]:
#proses pencarian hyperparameter
tuner.search(X_trainX, y_trainX,
             epochs = 25,
             validation_data = [X_valid, y_valid],
             callbacks = [stop_early])

Trial 23 Complete [00h 07m 25s]
val_accuracy: 0.09984000027179718

Best val_accuracy So Far: 0.1006999984383583
Total elapsed time: 01h 44m 06s
INFO:tensorflow:Oracle triggered exit

In [ ]:
best_hps = tuner.get_best_hyperparameters()[0]

print("Best number of layers: ", best_hps.get("layer"))
print("Best number of neuron: ", best_hps.get("neuron"))
print("Best number of epochs: ", best_hps.get("tuner/epochs"))

Best number of layers:  3
Best number of neuron:  400
Best number of epochs:  3

In [ ]:
model = tuner.hypermodel.build(best_hps) #build_model

In [ ]:
model.fit(X_trainX, y_trainX,
          epochs = 3,
          validation_data = [X_valid, y_valid])

Epoch 1/3
3233/3233 [==============================] - 29s 9ms/step - loss: 2.3028 - accuracy: 0.0997 - val_loss: 2.3028 - val_accuracy: 0.0998
Epoch 2/3
3233/3233 [==============================] - 29s 9ms/step - loss: 2.3027 - accuracy: 0.0985 - val_loss: 2.3027 - val_accuracy: 0.1000
Epoch 3/3
3233/3233 [==============================] - 30s 9ms/step - loss: 2.3028 - accuracy: 0.0999 - val_loss: 2.3026 - val_accuracy: 0.1003

In [ ]:
#memprediksi dengan model
model.evaluate(X_test, Y_test)

1980/1980 [==============================] - 7s 3ms/step - loss: 2.3464 - accuracy: 0.1011

[2.346377372741699, 0.10105744749307632]

In [ ]:
y_proba = model.predict(X_test)
y_proba

y_p = np.array([np.argmax(i) for i in y_proba])
print(y_p)

[2 0 0 ... 0 0 0]

hidden layer

neuron hidden layer

metode optimisasi

hyperparmeter turning